name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Move build files to assets folder
        run: |
          mkdir -p assets
          mv dist/assets/js/app.js assets/
          mv dist/assets/css/styles.css assets/

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          ftp-server: 'ftp.caribito.com'
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: 'assets'
          remote-dir: '/assets'
