name: Deploy to Production (/bill)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: 'ftp.caribito.com'
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './dist/'
          server-dir: '/bill/'
          # Este plugin maneja los deltas, solo subirá lo que cambie
